name: Quality Check

on: [pull_request]

env:
  UV_SYSTEM_PYTHON: 1

jobs:
  check_code_quality:
    runs-on: ubuntu-latest
    env:
      UV_HTTP_TIMEOUT: 600 # max 10min to install deps

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6
        with:
          python-version: "3.12"

      # Setup venv
      - name: Setup uv
        run: |
          pip install --upgrade uv

      - name: Install dependencies
        run: uv pip install "smolagents[quality] @ ."

      # Equivalent of "make quality" but step by step
      - run: ruff check examples src tests  # linter
      - run: ruff format --check examples src tests  # formatter
